- name: Télécharger le script d'installation de GitLab
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
    dest: /tmp/gitlab-install.sh
    mode: '0755'

- name: Exécuter le script d'installation de GitLab
  command: bash /tmp/gitlab-install.sh

- name: Mettre a jour le cache apt après le script GitLab
  apt:
    update_cache: yes

- name: Install GitLab EE
  apt:
    name: gitlab-ee
    state: present

- name: Configurer le domaine GitLab
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: "external_url 'http://{{ gitlab_domain }}'"
  notify: Redémarrer GitLab
  become: yes

- name: Configurer le chemin de stockage de GitLab
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^git_data_dirs'
    line: 'git_data_dirs({"default" => {"path" => "{{ gitlab_storage_path }}"}})'
  notify: Redémarrer GitLab
  become: yes
